/* ================================================================
   GALERIE PHOTOS
   Fichier mis à jour par l'espace admin : https://ongvici.org/admin/
   Chaque photo : [fichier, légende, catégorie]. Le fichier est relatif
   au dossier assets/img/galerie/.
   ================================================================ */

const GALERIE = [
    ["../projets/renovation-epp/inauguration-ruban.jpg","EPP SICOGI 1 — Coupure du ruban devant le bloc sanitaire rénové, 9 septembre 2026","ceremonie"],
    ["../projets/renovation-epp/inauguration-groupe.jpg","EPP SICOGI 1 — Élèves, enseignants et partenaires devant les nouvelles toilettes","ceremonie"],
    ["../projets/renovation-epp/inauguration-discours.jpg","EPP SICOGI 1 — Discours de la Présidente Wassia MADOU lors de l'inauguration","ceremonie"],
    ["../projets/renovation-epp/inauguration-visite.jpg","EPP SICOGI 1 — Les invités visitent les sanitaires rénovés","ceremonie"],
    ["../projets/renovation-epp/inauguration-officiels.jpg","EPP SICOGI 1 — Photo officielle avec les élèves et les autorités","ceremonie"],
    ["../projets/renovation-epp/ceremonie-officiel.jpg","Accueil des officiels lors de l'inauguration — 9 septembre 2026","ceremonie"],
    ["../projets/renovation-epp/ceremonie-equipe.jpg","Cérémonie d'inauguration — Bénévoles avec le drapeau de Verdis","ceremonie"],
    ["../projets/renovation-epp/ceremonie-vc.jpg","Membre de l'ONG devant la bannière Vision Citoyenne","ceremonie"],
    ["../projets/renovation-epp/ceremonie-ippdr.jpg","Bannière IPPDR lors de la cérémonie d'inauguration de l'EPP SICOGI 1","ceremonie"],
    ["../projets/renovation-epp/don-kits-hygiene.jpg","EPP SICOGI 1 — Kits d'hygiène offerts à l'école : seaux, balais et savon liquide","don"],
    ["../projets/renovation-epp/don-kits-scolaires.jpg","EPP SICOGI 1 — Remise de kits scolaires aux élèves","don"],
    ["../projets/renovation-epp/apres-toilettes.jpg","EPP SICOGI 1 — Le bloc « Toilettes » repeint, sol pavé et regards neufs","apres"],
    ["../projets/renovation-epp/apres-mur-accueil.jpg","EPP SICOGI 1 — Nouveau mur d'accueil « Bienvenue au Préscolaire SICOGI 1 »","apres"],
    ["../projets/renovation-epp/apres-aire-jeux-vue.jpg","EPP SICOGI 1 — L'aire de jeux terminée : balançoires, toboggan et fresque des chiffres","apres"],
    ["../projets/renovation-epp/apres-bloc-toilettes.jpg","EPP SICOGI 1 — Bloc sanitaire rénové et bordures en pneus recyclés","apres"],
    ["../projets/renovation-epp/apres-manege.jpg","EPP SICOGI 1 — Manège et balançoires installés pour les plus petits","apres"],
    ["../projets/renovation-epp/apres-toboggan.jpg","EPP SICOGI 1 — Toboggan neuf devant la fresque éducative","apres"],
    ["../projets/renovation-epp/apres-fresque-alphabet.jpg","EPP SICOGI 1 — Fresque éducative « abcd 1234 » terminée","apres"],
    ["../projets/renovation-epp/apres-cour-ensemble.jpg","EPP SICOGI 1 — Vue d'ensemble de la cour rénovée","apres"],
    ["../projets/renovation-epp/apres-cour-regards.jpg","EPP SICOGI 1 — Cour assainie : regards neufs et espaces délimités","apres"],
    ["../projets/renovation-epp/apres-aire-jeux.jpg","EPP SICOGI 1 — Mobilier de jeux neuf pour les enfants","apres"],
    ["../projets/renovation-epp/apres-cour.jpg","EPP SICOGI 1 — Aire de jeux avec fresque murale éducative","apres"],
    ["../projets/renovation-epp/apres-batiment.jpg","EPP SICOGI 1 — Bâtiments et espaces rénovés","apres"],
    ["../projets/renovation-epp/travaux-fosse.jpg","EPP SICOGI 1 — Construction d'une nouvelle fosse : pose des parpaings","travaux"],
    ["../projets/renovation-epp/travaux-fosse-maconnerie.jpg","EPP SICOGI 1 — Maçonnerie de la fosse septique","travaux"],
    ["../projets/renovation-epp/travaux-regard.jpg","EPP SICOGI 1 — Regard de filtration rempli de gravier","travaux"],
    ["../projets/renovation-epp/travaux-bloc.jpg","EPP SICOGI 1 — Terrassement autour du bloc sanitaire","travaux"],
    ["../projets/renovation-epp/travaux-bordures.jpg","EPP SICOGI 1 — Pose des bordures de la cour","travaux"],
    ["../projets/renovation-epp/travaux-cabines-carrelees.jpg","EPP SICOGI 1 — Cabines de toilettes entièrement carrelées","travaux"],
    ["../projets/renovation-epp/travaux-carrelage.jpg","EPP SICOGI 1 — Carrelage neuf dans les sanitaires","travaux"],
    ["../projets/renovation-epp/travaux-peinture-bloc.jpg","EPP SICOGI 1 — Mise en peinture du bloc « Toilettes »","travaux"],
    ["../projets/renovation-epp/travaux-mur-accueil.jpg","EPP SICOGI 1 — Préparation du nouveau mur d'accueil","travaux"],
    ["../projets/renovation-epp/travaux-fresque-debut.jpg","EPP SICOGI 1 — Début de la fresque : le ciel et le soleil","travaux"],
    ["../projets/renovation-epp/travaux-fresque.jpg","EPP SICOGI 1 — La fresque prend forme","travaux"],
    ["../projets/renovation-epp/travaux-fresque-alphabet.jpg","EPP SICOGI 1 — Finitions de la fresque éducative","travaux"],
    ["../projets/renovation-epp/avant-sanitaires.jpg","EPP SICOGI 1 — État des sanitaires avant rénovation, juillet 2026","avant"],
    ["../projets/renovation-epp/avant-cabine.jpg","EPP SICOGI 1 — Cabine de toilettes vétuste avant les travaux","avant"],
    ["../projets/renovation-epp/avant-ecole.jpg","EPP SICOGI 1 — Salle d'eau dégradée : murs tachés, carrelage abîmé","avant"],
    ["../projets/renovation-epp/avant-cabine-2.jpg","EPP SICOGI 1 — Toilettes sans porte ni revêtement","avant"],
    ["../projets/renovation-epp/avant-evacuation.jpg","EPP SICOGI 1 — Évacuation dégradée et sol souillé","avant"],
    ["../projets/renovation-epp/avant-cabine-exterieur.jpg","EPP SICOGI 1 — Ancienne cabine extérieure, peinture écaillée","avant"],
    ["../projets/renovation-epp/avant-mur-bloc.jpg","EPP SICOGI 1 — L'ancien mur « Bienvenue » et le bloc sanitaire","avant"],
    ["../projets/renovation-epp/avant-cour.jpg","EPP SICOGI 1 — Sol de terre et déchets au pied du mur d'accueil","avant"],
    ["../projets/renovation-epp/avant-dechets.jpg","EPP SICOGI 1 — Déchets évacués lors du nettoyage du site","avant"],
    ["../projets/pasea/remise-kits-tpe.jpg","PASEA Hambol — Lancement officiel à Katiola : les TPE et leurs équipements, 13 juin 2026","pasea-lancement"],
    ["../projets/pasea/ceremonie-remise-kits.jpg","PASEA Hambol — Cérémonie de lancement officiel au Conseil régional, Katiola, 13 juin 2026","pasea-lancement"],
    ["../projets/pasea/lancement-autorites.jpg","PASEA Hambol — Autorités et invités lors du lancement officiel, 13 juin 2026","pasea-lancement"],
    ["../projets/pasea/lancement-equipements.jpg","PASEA Hambol — Équipements remis aux TPE : brouettes, moules, cuvettes, protections","pasea-lancement"],
    ["../projets/pasea/formation-artisans.jpg","PASEA Hambol — Formation des artisans aux techniques de construction, juin 2026","pasea-form"],
    ["../projets/pasea/formation-salle.jpg","PASEA Hambol — Session de formation des membres des TPE, juin 2026","pasea-form"],
    ["../projets/pasea/formation-echanges.jpg","PASEA Hambol — Temps d'échange pendant la formation, juin 2026","pasea-form"],
    ["../projets/pasea/formation-securite.jpg","PASEA Hambol — Formation en tenue de sécurité, juin 2026","pasea-form"],
    ["../projets/pasea/tpe-formees.jpg","PASEA Hambol — Les artisans des TPE réunis après la formation","pasea-form"],
    ["../projets/pasea/mobilisation-village.jpg","PASEA Hambol — Réunion de mobilisation communautaire dans un village","pasea-mob"],
    ["../projets/pasea/reunion-communautaire.jpg","PASEA Hambol — Présentation du projet aux habitants","pasea-mob"],
    ["../projets/pasea/sensibilisation-menages.jpg","PASEA Hambol — Échanges avec les ménages sur l'assainissement familial","pasea-mob"],
    ["../projets/pasea/equipe-tpe.jpg","PASEA Hambol — Équipe d'une TPE avec ses équipements de protection","pasea-chantier"],
    ["../projets/pasea/tpe-chantier.jpg","PASEA Hambol — Artisans des TPE réunis sur un chantier","pasea-chantier"],
    ["../projets/pasea/implantation-latrine.jpg","PASEA Hambol — Implantation d'une latrine chez un ménage","pasea-chantier"],
    ["../projets/pasea/ferraillage-dalle.jpg","PASEA Hambol — Ferraillage d'une dalle","pasea-chantier"],
    ["../projets/pasea/moulage-fosse.jpg","PASEA Hambol — Mise en place du moule d'une fosse","pasea-chantier"],
    ["../projets/pasea/fosses-cuvette-sato.jpg","PASEA Hambol — Double fosse et cuvette SaTo avant la pose de la cabine","pasea-chantier"],
    ["../projets/pasea/construction-cabine.jpg","PASEA Hambol — Construction de la cabine en parpaings","pasea-chantier"],
    ["../projets/pasea/construction-superstructure.jpg","PASEA Hambol — Élévation de la superstructure","pasea-chantier"],
    ["../projets/pasea/finitions-latrine.jpg","PASEA Hambol — Finitions et pose de la tuyauterie","pasea-chantier"],
    ["../projets/pasea/latrine-livree.jpg","PASEA Hambol — Une latrine familiale terminée","pasea-chantier"],
    ["../projets/pasea/remise-latrine-menage.jpg","PASEA Hambol — Remise de la latrine au ménage bénéficiaire","pasea-chantier"],
    ["don-unicef-materiel.jpg","Don UNICEF : matériel d'hygiène remis au Lycée Moderne Inagohi — San Pedro","don"],
    ["don-unicef-remise.jpg","Remise officielle du don UNICEF aux élèves et au personnel du lycée","don"],
    ["don-unicef-groupe.jpg","Photo de groupe lors de la remise du don UNICEF — Mars 2022","don"],
    ["engagement-citoyen-ecole.jpg","Sensibilisation scolaire « Engagement Citoyen » auprès des élèves","sensibilisation"],
    ["sensibilisation-classe.jpg","Intervention en classe : hygiène et lavage des mains","sensibilisation"],
    ["mobilisation-scolaire.jpg","Mobilisation dans la cour de l'école — Engagement Citoyen, Mai 2022","sensibilisation"],
    ["sensibilisation-eleves.jpg","Les élèves participent activement à la sensibilisation","sensibilisation"],
    ["distribution-hygiene.jpg","Distribution de kits d'hygiène et de produits d'entretien","terrain"],
    ["distribution-nord.jpg","Remise de matériel dans une école du Nord — Mai 2022","terrain"],
    ["equipe-terrain.jpg","L'équipe Vision Citoyenne sur le terrain","terrain"],
    ["action-terrain-ecole.jpg","Action de terrain dans une école partenaire","terrain"],
    ["suivi-projet.jpg","Suivi et évaluation de projet dans un établissement scolaire","terrain"]
];
